"""Built-in TUI theme color definitions."""

THEMES: dict[str, dict] = {
    "dracula": {
        "name": "dracula",
        "dark": True,
        "primary": "#bd93f9",
        "secondary": "#ff79c6",
        "accent": "#50fa7b",
        "warning": "#ffb86c",
        "error": "#ff5555",
        "success": "#50fa7b",
        "surface": "#282a36",
        "panel": "#44475a",
        "boost": "#6272a4",
        "text": "#f8f8f2",
    },
    "nord": {
        "name": "nord",
        "dark": True,
        "primary": "#88c0d0",
        "secondary": "#81a1c1",
        "accent": "#a3be8c",
        "warning": "#d08770",
        "error": "#bf616a",
        "success": "#a3be8c",
        "surface": "#2e3440",
        "panel": "#3b4252",
        "boost": "#4c566a",
        "text": "#eceff4",
    },
    "catppuccin": {
        "name": "catppuccin",
        "dark": True,
        "primary": "#cba6f7",
        "secondary": "#f5c2e7",
        "accent": "#a6e3a1",
        "warning": "#fab387",
        "error": "#f38ba8",
        "success": "#a6e3a1",
        "surface": "#1e1e2e",
        "panel": "#313244",
        "boost": "#45475a",
        "text": "#cdd6f4",
    },
    "monokai": {
        "name": "monokai",
        "dark": True,
        "primary": "#a6e22e",
        "secondary": "#f92672",
        "accent": "#66d9ef",
        "warning": "#e6db74",
        "error": "#f92672",
        "success": "#a6e22e",
        "surface": "#272822",
        "panel": "#3e3d32",
        "boost": "#75715e",
        "text": "#f8f8f2",
    },
}
